import type { DrawingAsset, ModelResult, ModelSource } from '../types'

/**
 * THE BACKEND SEAM.
 *
 * The cinematic scene and the viewer never reference a model path directly.
 * They read `ModelResult` out of the store, and the store is filled by
 * whatever `ModelSource` is active here.
 *
 * Claude Account 2: implement `HttpModelSource` (or similar) below and change
 * `activeModelSource` at the bottom of this file. Nothing else in the app has
 * to change - no component imports DEMO_MODEL_URL.
 */

/**
 * The local placeholder model. Generated by `scripts/generate-demo-model.mjs`
 * and committed to `public/models/demo.glb`.
 *
 * Replace by returning a different `modelUrl` from a ModelSource - do NOT
 * change this constant to point at a backend URL, because it is also the
 * offline fallback.
 */
export const DEMO_MODEL_URL = '/models/demo.glb'

/** Simulated pipeline latency, so loading states are exercised in dev. */
const MOCK_LATENCY_MS = 650

function delay(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new DOMException('Aborted', 'AbortError'))
      return
    }
    const id = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort)
      resolve()
    }, ms)
    function onAbort() {
      clearTimeout(id)
      reject(new DOMException('Aborted', 'AbortError'))
    }
    signal?.addEventListener('abort', onAbort, { once: true })
  })
}

/**
 * The implementation used today.
 *
 * It ignores the drawing content entirely (no OCR, no interpretation - that is
 * explicitly out of scope) and resolves to the committed demo GLB. The user's
 * own drawing preview is threaded through as `originalDrawingUrl` so the
 * viewer's Original / Split modes show the real uploaded sheet.
 */
export class MockModelSource implements ModelSource {
  async requestModel(drawing: DrawingAsset, signal?: AbortSignal): Promise<ModelResult> {
    await delay(MOCK_LATENCY_MS, signal)
    return {
      jobId: 'mock_' + Date.now().toString(36),
      status: 'complete',
      modelUrl: DEMO_MODEL_URL,
      originalDrawingUrl: drawing.previewUrl,
    }
  }
}

/* -------------------------------------------------------------------------- */
/* TODO(Claude Account 2) - real backend implementation                       */
/* -------------------------------------------------------------------------- */

/**
 * Sketch of the eventual implementation. Intentionally NOT wired up.
 *
 * The expected job lifecycle is:
 *   POST  /api/jobs            (multipart: the PDF)        -> { jobId }
 *   GET   /api/jobs/:id                                    -> ModelResult
 *   ...poll or subscribe until status is complete | failed | needs_input
 *
 * `status: 'needs_input'` carries `questions[]` for the missing-dimension
 * workflow. The frontend types that case already (see types/index.ts) but
 * renders no UI for it yet - that is Account 2's to build, and the natural
 * place is a new state between `uploaded` and `bookOpening` in
 * `state/machine.ts`.
 *
 * Keep the returned shape conformant to `ModelResult` and the cinematic
 * sequence will not need to change.
 */
// export class HttpModelSource implements ModelSource {
//   constructor(private readonly baseUrl: string) {}
//
//   async requestModel(drawing: DrawingAsset, signal?: AbortSignal): Promise<ModelResult> {
//     const body = new FormData()
//     body.append('drawing', drawing.file, drawing.fileName)
//     const created = await fetch(`${this.baseUrl}/api/jobs`, { method: 'POST', body, signal })
//     const { jobId } = await created.json()
//     return this.poll(jobId, signal)
//   }
//
//   private async poll(jobId: string, signal?: AbortSignal): Promise<ModelResult> { ... }
// }

/**
 * The source the application uses. Swap this one binding to go live.
 */
export const activeModelSource: ModelSource = new MockModelSource()
